name: Manually workflow
on:
  workflow_dispatch:
    inputs:
      flavours:
        description: 'flavours'
        required: true
        default: 'assembleDebug'
      tags:
        description: 'Test scenario tags'
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew ${{ github.event.inputs.flavours }} --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk